version: '3'

services:
  maxtec_site:
    build: .
    ports:
      - 3000:3000
    container_name: 'maxtec_site'
    volumes:
      - ./:/app
      - /app/.next
      - node_modules:/app/node_modules

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules